folio-org/mod-circulation-bff

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, PERSONAL_DATA_DISCLOSURE.md, README.md
[MCBFF-1](https://folio-org.atlassian.net/browse/MCBFF-1) Add initial files
https://dev.folio.org/guidelines/create-new-repo/
=> MCBFF-1 Add initial files

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/circulationbff/CirculationBffApplication.java, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java, src/main/java/org/folio/circulationbff/controller/TenantController.java, src/test/java/org/folio/circulationbff/api/BaseIT.java, src/test/java/org/folio/circulationbff/api/TenantApiTest.java
[MCBFF-8](https://folio-org.atlassian.net/browse/MCBFF-8)
`POST /_/tenant` returned 404
Implement tenant API, return 204 No content for all methods - POST, DELETE, GET
=> MCBFF-8 Implement tenant API

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/circulationbff/client/SearchClient.java, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java, src/main/java/org/folio/circulationbff/service/SearchService.java, src/main/java/org/folio/circulationbff/service/impl/SearchServiceImpl.java, src/main/resources/application.yml, src/test/java/org/folio/circulationbff/api/BaseIT.java, src/test/java/org/folio/circulationbff/api/CirculationBffRequestsApiTest.java, src/test/java/org/folio/circulationbff/controller/CirculationBffControllerTest.java, src/test/java/org/folio/circulationbff/service/SearchServiceTest.java
[MCBFF-3](https://folio-org.atlassian.net/browse/MCBFF-3)
=> MCBFF-3: Proxy instance search calls to mod-search

src/main/java/org/folio/circulationbff/controller/CirculationBffController.java
1 line bug fix regarding [MCBFF-5](https://folio-org.atlassian.net/browse/MCBFF-6)
=> [MCBFF-5] BFF for allowed service points functionality (bug fix)

descriptors/ModuleDescriptor-template.json
Resolves: [MCBFF-10](https://folio-org.atlassian.net/browse/MCBFF-10)
=> [MCBFF-10] Fix permission set name

descriptors/ModuleDescriptor-template.json
=>  MCBFF-4: fix holdings-storage interface

NEWS.md, pom.xml
[MCBFF-14](https://folio-org.atlassian.net/browse/MCBFF-14)
=> MCBFF-14 Release mod-circulation-bff v1.0.0

pom.xml, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java
Update folio-spring-support to 8.2
[MCBFF-15](https://folio-org.atlassian.net/browse/MCBFF-15)
=> MCBFF-15: Update folio-spring-support to 8.2

descriptors/ModuleDescriptor-template.json, src/main/resources/swagger.api/schemas/dto/request/BffRequest.yaml
Covers: [MCBFF-6](https://folio-org.atlassian.net/browse/MCBFF-6)
Increase version, fixed typo requestLevel
=> MCBFF-6 Increase minor version, fix typo requestLevel

src/main/java/org/folio/circulationbff/client/feign/EcsTlrClient.java, src/test/java/org/folio/circulationbff/api/StaffSlipsApiTestDataProvider.java
Fix incorrect URLs.
[MCBFF-12](https://folio-org.atlassian.net/browse/MCBFF-12)
=> MCBFF-12: Fix staff slips URLs

descriptors/ModuleDescriptor-template.json
MCBFF-24
Add metadata section with system user info to module descriptor
=> MCBFF-24 Add system user to module descriptor

descriptors/ModuleDescriptor-template.json
MCBFF-26 
- Add tlr settings interface dependency
- Move requests mediated dependency to optional
=> MCBFF-26 Add tlr settings interface dependency

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/circulationbff/client/feign/UserClient.java, src/main/java/org/folio/circulationbff/domain/dto/AllowedServicePointParams.java, src/main/java/org/folio/circulationbff/service/UserService.java, src/main/java/org/folio/circulationbff/service/impl/CirculationBffServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/UsersServiceImpl.java, src/test/java/org/folio/circulationbff/api/CirculationBffRequestsApiTest.java
https://folio-org.atlassian.net/browse/MCBFF-25
Pass patron group id
=> MCBFF-25: Pass patron group to allowed SP call for non-central ECS case

src/main/resources/swagger.api/schemas/dto/staffSlips/staffSlip.yaml
https://folio-org.atlassian.net/browse/MCBFF-27
=> MCBFF-27: Fix staff slip token name

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java, src/main/java/org/folio/circulationbff/service/EcsRequestExternalService.java, src/main/java/org/folio/circulationbff/service/impl/EcsRequestExternalServiceImpl.java, src/main/resources/swagger.api/paths/ecsRequestExternal/ecsRequestExternal.yaml, src/test/java/org/folio/circulationbff/api/EcsExternalRequestApiTest.java
Resolves: [MCBFF-32](https://folio-org.atlassian.net/browse/MCBFF-32)
=> MCBFF-32 Endpoint create-ecs-request-external should return circulation request

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/circulationbff/client/feign/CheckInClient.java, src/main/java/org/folio/circulationbff/client/feign/CirculationClient.java, src/main/java/org/folio/circulationbff/client/feign/config/ErrorForwardingFeignClientConfiguration.java, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java, src/main/java/org/folio/circulationbff/exception/HttpFailureFeignException.java, src/main/java/org/folio/circulationbff/service/CheckInService.java, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/paths/check-in/check-in.yaml, src/main/resources/swagger.api/schemas/dto/circulation/check-in-request.yaml, src/main/resources/swagger.api/schemas/dto/circulation/check-in-response.yaml, src/main/resources/swagger.api/schemas/response/check-in-response.yaml, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
Create a proxy endpoint for mod-circulation's Check-in API.
[MCBFF-37](https://folio-org.atlassian.net/browse/MCBFF-37)
=> MCBFF-37: Check-in API

descriptors/ModuleDescriptor-template.json, src/main/resources/swagger.api/circulation-bff.yaml, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
Change URL from `/circulation-bff/check-in-by-barcode` to `/circulation-bff/loans/check-in-by-barcode`
[MCBFF-37](https://folio-org.atlassian.net/browse/MCBFF-37)
=> MCBFF-37 Change URL to `/circulation-bff/loans/check-in-by-barcode`

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/circulationbff/client/feign/CheckInClient.java, src/main/java/org/folio/circulationbff/client/feign/CirculationClient.java, src/main/java/org/folio/circulationbff/client/feign/config/ErrorForwardingFeignClientConfiguration.java, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java, src/main/java/org/folio/circulationbff/exception/HttpFailureFeignException.java, src/main/java/org/folio/circulationbff/service/CheckInService.java, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/paths/check-in/check-in.yaml, src/main/resources/swagger.api/schemas/dto/circulation/check-in-request.yaml, src/main/resources/swagger.api/schemas/response/check-in-response.yaml, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
Resolves: [MCBFF-39](https://folio-org.atlassian.net/browse/MCBFF-39)
=> MCBFF-39 Release 1.0.4

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
Resolves: [MCBFF-42](https://folio-org.atlassian.net/browse/MCBFF-42)
=> MCBFF-42 Release v1.0.5

src/main/java/org/folio/circulationbff/service/impl/CirculationBffServiceImpl.java, src/test/java/org/folio/circulationbff/api/CirculationBffRequestsApiTest.java
https://folio-org.atlassian.net/browse/MCBFF-36
=> MCBFF-36: fixed NPE for getAllowedServicePoints in case of replace operation when editing Non ECS Page request

NEWS.md, pom.xml, src/main/java/org/folio/circulationbff/service/impl/CirculationBffServiceImpl.java, src/test/java/org/folio/circulationbff/api/CirculationBffRequestsApiTest.java
https://folio-org.atlassian.net/browse/MCBFF-45
=> Bugfix release 1.0.6

src/main/java/org/folio/circulationbff/service/impl/CirculationBffServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/UserTenantsServiceImpl.java, src/test/java/org/folio/circulationbff/api/CirculationBffRequestsApiTest.java
MCBFF-52
Check the diagram in the MCBFF-52 description
=> MCBFF-52 Change Allowed SP routing implementation

NEWS.md, pom.xml, src/main/java/org/folio/circulationbff/service/impl/CirculationBffServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/UserTenantsServiceImpl.java, src/test/java/org/folio/circulationbff/api/CirculationBffRequestsApiTest.java
https://folio-org.atlassian.net/browse/MCBFF-59
=> Bugfix release 1.0.7

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/circulationbff/client/feign/LocationCampusClient.java, src/main/java/org/folio/circulationbff/client/feign/LocationInstitutionClient.java, src/main/java/org/folio/circulationbff/client/feign/LocationLibraryClient.java, src/main/java/org/folio/circulationbff/service/InventoryService.java, src/main/java/org/folio/circulationbff/service/SearchService.java, src/main/java/org/folio/circulationbff/service/UserTenantsService.java, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/InventoryServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/SearchServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/UserTenantsServiceImpl.java, src/main/resources/permissions/mod-circulation-bff.csv, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/schemas/dto/inventory/campus.json, src/main/resources/swagger.api/schemas/dto/inventory/campuses.json, src/main/resources/swagger.api/schemas/dto/inventory/institution.json, src/main/resources/swagger.api/schemas/dto/inventory/institutions.json, src/main/resources/swagger.api/schemas/dto/inventory/libraries.json, src/main/resources/swagger.api/schemas/dto/inventory/library.json, src/main/resources/swagger.api/schemas/response/check-in-response.yaml, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java, src/test/java/org/folio/circulationbff/service/SearchServiceTest.java
Resolves: [MCBFF-62](https://folio-org.atlassian.net/browse/MCBFF-62)
=> MCBFF-62 Release 1.0.8 

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/main/resources/swagger.api/schemas/response/check-in-response.yaml, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
Fields that needs to be updated with real item (data tenant item) information:
- inTransitDestinationServicePointId
- inTransitDestinationServicePoint.id
- inTransitDestinationServicePoint.name
- location.name
- holdingsRecordId
- instanceId
Resolves: [MCBFF-67](https://folio-org.atlassian.net/browse/MCBFF-67)
=> MCBFF-67 Rebuild 'item' part of the check-in response

descriptors/ModuleDescriptor-template.json
MCBFF-44
Revert interface version
=> MCBFF-44 Revert interface version

src/main/resources/swagger.api/schemas/response/check-in-response.yaml
Resolves: [MCBFF-67](https://folio-org.atlassian.net/browse/MCBFF-67)
=> MCBFF-67 Add additionalProperties

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/circulationbff/client/feign/CheckOutClient.java, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java, src/main/java/org/folio/circulationbff/service/CheckOutService.java, src/main/java/org/folio/circulationbff/service/impl/CheckOutServiceImpl.java, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/paths/check-out/check-out.yaml, src/main/resources/swagger.api/schemas/dto/circulation/check-out-request.yaml, src/main/resources/swagger.api/schemas/response/check-out-response.yaml, src/test/java/org/folio/circulationbff/api/CheckOutApiTest.java
https://folio-org.atlassian.net/browse/MCBFF-68
Create new check-out-by-barcode endpoint.
=> MCBFF-68: Check-out API

Dockerfile, Jenkinsfile, pom.xml, src/test/resources/mappings/users.json
https://folio-org.atlassian.net/browse/FOLREL-715
Update java and dependency versions.
=> FOLREL-715: Update to Java 21

README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/permissions/mod-circulation-bff.csv
Resolves: [MCBFF-77](https://folio-org.atlassian.net/browse/MCBFF-77)
=> MCBFF-77 Add mod-settings permissions to the system user

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/circulationbff/client/feign/EcsTlrClient.java, src/main/java/org/folio/circulationbff/service/impl/CheckOutServiceImpl.java, src/main/resources/permissions/mod-circulation-bff.csv, src/test/java/org/folio/circulationbff/api/CheckOutApiTest.java
https://folio-org.atlassian.net/browse/MCBFF-79
=> Bugfix release 1.0.13

NEWS.md, pom.xml
Resolves: [MCBFF-80](https://folio-org.atlassian.net/browse/MCBFF-80)
=> MCBFF-80 Release 1.1.0

src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
Covers: [MCBFF-75](https://folio-org.atlassian.net/browse/MCBFF-75)
If the Item has a CN, populate with Item CN. If no CN in Item, populate the CN with the Holdings record CN.
=> MCBFF-75 Populate the CN with the Holdings record CN if item's CN is empty

NEWS.md, pom.xml, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
Resolves: [MCBFF-84](https://folio-org.atlassian.net/browse/MCBFF-84)
=> MCBFF-84 Release 1.0.14

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/circulationbff/client/feign/LoanTypeClient.java, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/SearchServiceImpl.java, src/main/resources/permissions/mod-circulation-bff.csv, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/schemas/dto/inventory/item.json, src/main/resources/swagger.api/schemas/dto/inventory/loanType.json, src/main/resources/swagger.api/schemas/dto/inventory/loanTypes.json, src/main/resources/swagger.api/schemas/dto/search/bffSearchItem.yaml, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java, src/test/java/org/folio/circulationbff/api/SearchInstancesApiTest.java
Resolves: [MCBFF-91](https://folio-org.atlassian.net/browse/MCBFF-91)
=> MCBFF-91 Release 1.1.1

descriptors/ModuleDescriptor-template.json, src/main/resources/swagger.api/schemas/dto/allowedServicePoint/allowedServicePoints.yaml, src/test/java/org/folio/circulationbff/util/MockHelper.java
https://folio-org.atlassian.net/browse/MCBFF-93
=> MCBFF-93: Added discoveryDisplayName in AllowedServicePoints response

src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
Covers: [MCBFF-88](https://folio-org.atlassian.net/browse/MCBFF-88)
=> [MCBFF-88] Returns workflow: Central tenant Check in of Item with Hold

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/circulationbff/client/feign/LoanStorageClient.java, src/main/java/org/folio/circulationbff/service/CirculationStorageService.java, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/CirculationStorageServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/TenantServiceImpl.java, src/main/java/org/folio/circulationbff/support/CqlQuery.java, src/main/resources/permissions/mod-circulation-bff.csv, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/schemas/dto/circulation/loan.json, src/main/resources/swagger.api/schemas/dto/circulation/loans.json, src/main/resources/swagger.api/schemas/dto/common/metadata.json, src/main/resources/swagger.api/schemas/dto/common/uuid.json, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java
[MCBFF-90](https://folio-org.atlassian.net/browse/MCBFF-90)
=> MCBFF-90: Close loan in secure tenant upon check-in in central tenant

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/resources/swagger.api/schemas/dto/allowedServicePoint/allowedServicePoints.yaml, src/test/java/org/folio/circulationbff/util/MockHelper.java
https://folio-org.atlassian.net/browse/MCBFF-96
=> Ramsons (CSP#3) release 1.0.15

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/circulationbff/client/feign/LoanStorageClient.java, src/main/java/org/folio/circulationbff/client/feign/LoanTypeClient.java, src/main/java/org/folio/circulationbff/service/CirculationStorageService.java, src/main/java/org/folio/circulationbff/service/impl/CheckInServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/CirculationStorageServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/SearchServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/TenantServiceImpl.java, src/main/java/org/folio/circulationbff/support/CqlQuery.java, src/main/resources/permissions/mod-circulation-bff.csv, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/schemas/dto/circulation/loan.json, src/main/resources/swagger.api/schemas/dto/circulation/loans.json, src/main/resources/swagger.api/schemas/dto/common/metadata.json, src/main/resources/swagger.api/schemas/dto/common/uuid.json, src/main/resources/swagger.api/schemas/dto/inventory/item.json, src/main/resources/swagger.api/schemas/dto/inventory/loanType.json, src/main/resources/swagger.api/schemas/dto/inventory/loanTypes.json, src/main/resources/swagger.api/schemas/dto/search/bffSearchItem.yaml, src/test/java/org/folio/circulationbff/api/CheckInApiTest.java, src/test/java/org/folio/circulationbff/api/SearchInstancesApiTest.java
[MCBFF-94](https://folio-org.atlassian.net/browse/MCBFF-94)
=> MCBFF-94: Release v1.0.16 (Ramsons CSP#3)

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/circulationbff/client/feign/CirculationClient.java, src/main/java/org/folio/circulationbff/controller/CirculationBffController.java, src/main/java/org/folio/circulationbff/domain/mapping/CirculationLoanMapper.java, src/main/java/org/folio/circulationbff/service/CirculationLoanService.java, src/main/java/org/folio/circulationbff/service/impl/CirculationLoanServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/SearchServiceImpl.java, src/main/resources/permissions/mod-circulation-bff.csv, src/main/resources/swagger.api/circulation-bff.yaml, src/main/resources/swagger.api/parameters/limit.yaml, src/main/resources/swagger.api/parameters/loanId.yaml, src/main/resources/swagger.api/parameters/offset.yaml, src/main/resources/swagger.api/parameters/totalRecords.yaml, src/main/resources/swagger.api/paths/loans/loanById.yaml, src/main/resources/swagger.api/paths/loans/loans.yaml, src/main/resources/swagger.api/schemas/dto/circulation/circulationLoan.yaml, src/main/resources/swagger.api/schemas/dto/circulation/circulationLoans.yaml, src/main/resources/swagger.api/schemas/dto/circulation/loanItem.yaml, src/main/resources/swagger.api/schemas/dto/search/baseSearchInstance.yaml, src/main/resources/swagger.api/schemas/dto/search/bffSearchItem.yaml, src/main/resources/swagger.api/schemas/dto/search/bffSearchItemCallNumberComponents.yaml, src/main/resources/swagger.api/schemas/dto/search/bffSearchItemInTransitDestinationServicePoint.yaml, src/test/java/org/folio/circulationbff/api/CirculationLoanApiTest.java, src/test/java/org/folio/circulationbff/service/CirculationLoanServiceTest.java, src/test/java/org/folio/circulationbff/util/CirculationLoanTestData.java, src/test/resources/mappings/users.json
https://folio-org.atlassian.net/browse/MCBFF-105
=> MCBFF-105: Ramsons (CSP#3) Release 1.0.18

src/main/java/org/folio/circulationbff/service/impl/SearchServiceImpl.java, src/test/java/org/folio/circulationbff/service/SearchServiceTest.java
[https://folio-org.atlassian.net/browse/MCBFF-107](https://folio-org.atlassian.net/browse/MCBFF-107)
Merge keys when creating a map
=> MCBFF-107 Handle duplicate item IDs in search response

pom.xml
[MCBFF-106](https://folio-org.atlassian.net/browse/MCBFF-106)
=> MCBFF-106: Fix local builds

src/main/java/org/folio/circulationbff/client/feign/GetByQueryParamsClient.java, src/main/java/org/folio/circulationbff/client/feign/HoldingsStorageClient.java, src/main/java/org/folio/circulationbff/client/feign/InstanceStorageClient.java, src/main/java/org/folio/circulationbff/client/feign/ItemStorageClient.java, src/main/java/org/folio/circulationbff/client/feign/LoanStorageClient.java, src/main/java/org/folio/circulationbff/client/feign/LoanTypeClient.java, src/main/java/org/folio/circulationbff/client/feign/LocationCampusClient.java, src/main/java/org/folio/circulationbff/client/feign/LocationClient.java, src/main/java/org/folio/circulationbff/client/feign/LocationInstitutionClient.java, src/main/java/org/folio/circulationbff/client/feign/LocationLibraryClient.java, src/main/java/org/folio/circulationbff/client/feign/MaterialTypeClient.java, src/main/java/org/folio/circulationbff/client/feign/SearchInstancesClient.java, src/main/java/org/folio/circulationbff/client/feign/ServicePointClient.java, src/main/java/org/folio/circulationbff/service/BulkFetchingService.java, src/main/java/org/folio/circulationbff/service/impl/BulkFetchingServiceImpl.java, src/main/java/org/folio/circulationbff/service/impl/SearchServiceImpl.java, src/test/java/org/folio/circulationbff/api/CirculationLoanApiTest.java, src/test/java/org/folio/circulationbff/service/BulkFetchingServiceTest.java
Search instances with item details.
https://folio-org.atlassian.net/browse/MCBFF-134
Add support for additional query parameters to `BulkFetchingService`.
=> MCBFF-134: Search instances with `expandAll=true`

descriptors/ModuleDescriptor-template.json
=> MCBFF-133: Update version of interface `requests-mediated-loans`

src/main/java/org/folio/circulationbff/service/impl/InventoryServiceImpl.java, src/test/java/org/folio/circulationbff/api/InventoryItemsApiTest.java
MCBFF-136 Remove quotes from barcode
=> MCBFF-136 Remove quotes from barcode

src/main/resources/swagger.api/paths/ecsRequestExternal.yaml, src/main/resources/swagger.api/paths/requests.yaml
https://folio-org.atlassian.net/browse/MCBFF-146
Replace component references with schema paths
=> MCBFF-146 Fix module compilation on Windows
